### ISSUE TITLE
Json document support

### ISSUE THREAD

**Issue by abnerjacobsen** [capless/docb#6]
Hi,

I would like to use Docb in a project but I have a question: 

Docb can handle documents like this ?

`{
  "person_id" : 123,
  "last_name" : "Barr",
  "first_name" : "Jeff",
  "current_city" : "Tokyo",
  "next_haircut" :
  {
    "year" : 2014,
    "month" : 10,
    "day" : 30
  },
  "children"  :
    [ "SJB", "ASB", "CGB", "BGB", "GTB" ],
  "cars": [
        { "name":"Ford", "models":[ "Fiesta", "Focus", "Mustang" ] },
        { "name":"BMW", "models":[ "320", "X3", "X5" ] },
        { "name":"Fiat", "models":[ "500", "Panda" ] }
    ]
}`

**Comment by armicron** [comment]
Hello. It can't.

**Comment by alshapton** [comment]
What is it specifically about the document that @abnerjacobsen illustrated that can't be handled by docb ?

**Comment by bjinwright** [comment]
DocB could handle the inserts but would fail to query it correctly if the filter was cars.
